export const UserActions = {
  LOGIN_USER: 'LOGIN_USER',
  REGISTER_USER: 'REGISTER_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  AUTH_USER_SUCCESS: 'AUTH_USER_SUCCESS',
  AUTH_USER_ERROR: 'AUTH_USER_ERROR',

  CREATE_USER: 'CREATE_USER',
  READ_USERS: 'READ_USERS',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  INVITE_USER: 'INVITE_USER',
  UPLOAD_AVATAR: 'UPLOAD_AVATAR',
  ACTION_USER_SUCCESS: 'ACTION_USER_SUCCESS',
  ACTION_USER_ERROR: 'ACTION_USER_ERROR',

  RESET_USER: 'RESET_USER',
};

export const ApartActions = {
  CREATE_APART: 'CREATE_APART',
  READ_APARTS: 'READ_APARTS',
  UPDATE_APART: 'UPDATE_APART',
  DELETE_APART: 'DELETE_APART',
  ACTION_APART_SUCCESS: 'ACTION_APART_SUCCESS',
  ACTION_APART_ERROR: 'ACTION_APART_ERROR',

  RESET_APART: 'RESET_APART',
};
